name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  manage-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: manage-releases
        run: |
          gh release delete latest
          gh release create latest
  build-apple:
    runs-on: macos-11
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.20.0
      - name: Install dmg maker
        run: brew install create-dmg
      - name: Create Apple dmg asset
        run: make release-mac
      - name: Upload apple release asset
        id: upload-apple-release-asset
        run: |
          gh release upload latest ./build/release/MacOS/PapeChanger.dmg
  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows
        run: |
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          make release-win
      - name: get release
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
          draft: false
          prerelease: true
      - name: Upluad Winodws Release Asset
        id: upload-windows-release-asset
        run: |
          gh release upload latest ./phonon.msi
